videos:
  7092083-hd_1920_1080_30fps.mp4:
    zones:
      - id: S01
        x1: 0.05
        y1: 0.40
        x2: 0.35
        y2: 0.95

      - id: S02
        x1: 0.25
        y1: 0.35
        x2: 0.50
        y2: 0.85

      - id: S03
        x1: 0.55
        y1: 0.35
        x2: 0.75
        y2: 0.80

      - id: S04
        x1: 0.60
        y1: 0.40
        x2: 0.95
        y2: 0.95

      - id: S05
        x1: 0.70
        y1: 0.30
        x2: 0.85
        y2: 0.60

videos:
  155164-809618953.mp4:
    zones:
      - id: S01
        x1: 0.00
        y1: 0.10
        x2: 0.20
        y2: 0.40
      - id: S02
        x1: 0.15
        y1: 0.15
        x2: 0.35
        y2: 0.45
      - id: S03
        x1: 0.30
        y1: 0.20
        x2: 0.65
        y2: 0.65
      - id: S04
        x1: 0.45
        y1: 0.10
        x2: 0.70
        y2: 0.45
      - id: S05
        x1: 0.55
        y1: 0.35
        x2: 0.95
        y2: 0.95
